name: qiblah_flutter
description: A compass qibla

publish_to: "none"

version: 1.0.5+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  dynamic_color: ^1.7.0
  flutter_qiblah: ^3.1.0+1
  flutter_svg: ^2.1.0
  geolocator: ^13.0.4
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
