name: qiblah_flutter
description: A compass qibla

publish_to: "none"

version: 1.0.3+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  flutter_qiblah: ^1.0.3+2
  geolocator: ^6.1.14
  flutter_svg: ^0.19.2+1

dev_dependencies:

flutter:
  uses-material-design: true

  assets:
    - assets/
