name: qiblah_flutter
description: A compass qibla

publish_to: "none"

version: 1.0.3+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  flutter_qiblah: ^3.1.0+1
  geolocator: ^13.0.4
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
